### ISSUE TITLE
Add Command Documentation Error

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#128]
**Describe the bug**
Example add command is incorrect.

**To Reproduce**
1. Go to User Guide.
2. Execute the add command provided:
<img width="909" alt="Screenshot 2019-04-03 at 12 33 11 PM" src="https://user-images.githubusercontent.com/32394182/55453008-b3581000-560c-11e9-96cd-bd60ce674f99.png">
3. See error:
<img width="1399" alt="Screenshot 2019-04-03 at 12 31 53 PM" src="https://user-images.githubusercontent.com/32394182/55453037-c79c0d00-560c-11e9-95c3-4b2ebf1538f4.png">

This example command does not work as well:
<img width="916" alt="Screenshot 2019-04-03 at 12 36 22 PM" src="https://user-images.githubusercontent.com/32394182/55453121-311c1b80-560d-11e9-9001-e69543546af6.png">

As with this:
<img width="1051" alt="Screenshot 2019-04-03 at 12 40 10 PM" src="https://user-images.githubusercontent.com/32394182/55453241-aab40980-560d-11e9-8af4-963bedee60e6.png">

**Expected behavior**
Should register a successful add.

Only `add n/MA1101R tutorial sd/14-03-19 st/12.00 ed/14-03-19 et/14.00 d/Tutorial 8 c/a` is working.

<hr>

**Reported by:** @marcus-pzj
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#37]</sub>

**Comment by cheahzk** [comment]
#147 There is a mistake in the user guide, done the updating. Thanks.
