### ISSUE TITLE
unable to delete after setting start and end time

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#129]
when adding a new task e.g.
add n/CS2113T sd/15-03-19 st/14.00 ed/15-03-19 et/14.35 d/Class diagram c/a t/urgent t/duesoon

If start time (look at st and et) is set to a flat hour like 14.00, 
when end time is set in the same hours but different minute,
the task is created but unable to be deleted.
Only works up to 14.35
the program still can be cleared, after which it works fine

<hr>

**Reported by:** @articstranger
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#48]</sub>

**Comment by cheahzk** [comment]
#148 Fixed this bug. Thanks.
