### ISSUE TITLE
Should not be allowed to input invalid dates for List .

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#130]
**Please describe the problem**
User is allowed to enter an invalid date for `list` command: haha-blabla-gaga, 0.1-33-3.1414314...

<img width="1264" alt="Screenshot 2019-04-03 at 12 44 30 PM" src="https://user-images.githubusercontent.com/32394182/55453470-a5a38a00-560e-11e9-8642-fe7b9b154dc7.png">
<img width="775" alt="Screenshot 2019-04-03 at 12 46 07 PM" src="https://user-images.githubusercontent.com/32394182/55453474-ab00d480-560e-11e9-8f5d-c5568be05de5.png">

**Describe the improvement you'd like to suggest**
Use Regex to allow only valid date inputs.

<hr>

**Reported by:** @marcus-pzj
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#65]</sub>

**Comment by ghost** [comment]
@BrittonAlone

**Comment by cheahzk** [comment]
#187 Fixed.
