### ISSUE TITLE
add command does not work per user guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#131]
I copied and pasted one of the command example i got from the user guide, but it did not work.

**To Reproduce**
1.  type the following into the terminal box
     add n/CS2113 task sd/13-03-19 st/12.00 ed/13-03-19 et/14.00 d/Talk about version control

**Expected behavior**
The task to be added into the task list. 

<hr>

**Reported by:** @jayrometan
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#66]</sub>

**Comment by cheahzk** [comment]
#147 There is a mistake in the user guide, done the updating. Thanks.
