### ISSUE TITLE
Tags names for edit should be alphanumeric, but example command shows otherwise

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#132]
**Describe the bug**
Documentation provided an invalid example for `edit` command.

**To Reproduce**
`edit 1 st/12.00 et/14.00 t/GET1018 tut`

**Expected behavior**
Successful edit.

**Screenshots**
<img width="927" alt="Screenshot 2019-04-03 at 12 49 34 PM" src="https://user-images.githubusercontent.com/32394182/55453629-38dcbf80-560f-11e9-8d2a-ff7b4fabcf98.png">
<img width="357" alt="Screenshot 2019-04-03 at 12 51 47 PM" src="https://user-images.githubusercontent.com/32394182/55453645-46924500-560f-11e9-9b62-0fc1ec4475eb.png">

<hr>

**Reported by:** @marcus-pzj
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#82]</sub>

**Comment by ghost** [comment]
@Wanchunwei

**Comment by Wanchunwei** [comment]
Thanks for finding this bug, we have change the example of our User Guide
