### ISSUE TITLE
The tasks does not disappear even after i have changed the month

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#133]
**Describe the bug**
Although i have changed the month, but the tasks at the side of the month does not change.

**To Reproduce**
1.  Add any task.
2. Enter month +
3. The task at the side does not change even though the task ended already.

**Expected behavior**
I would expect the task to disappear when i change months if the task ended the previous month.

![image](https://user-images.githubusercontent.com/34192985/55453636-3ed2a080-560f-11e9-9799-320a517ba1de.png)

<hr>

**Reported by:** @jayrometan
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#97]</sub>

**Comment by ghost** [comment]
@jingchen-z

**Comment by jingchen-z** [comment]
The section on the right of calendar is covered by 'reminder' feature. The calendar is just a calendar, it has nothing to do what tasks will be shown. But in the future version (v2.0+), we will change the colour for each day in the calendar to show the amount of tasks need to be done on that day!
