### ISSUE TITLE
The start up GUI does not match the one specified in the UserGuide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#134]
**Describe the bug**
The start up GUI does not match the one specified in the UserGuide

**To Reproduce**
1. Open the jar file.

**Expected behavior**
As indicated in the user guide, the GUI appears should be:
![Screenshot from 2019-04-03 12-54-07](https://user-images.githubusercontent.com/36043330/55453815-067f9200-5610-11e9-9a4d-83763aa33f14.png)

**Screenshots**
In actual GUI, the views are not properly displayed: ![Screenshot from 2019-04-03 12-53-54](https://user-images.githubusercontent.com/36043330/55453802-fa93d000-560f-11e9-8b59-c6203c1cb045.png)

**Additional context**
The Operating System I used to open the jar file is Ubuntu.

<hr>

**Reported by:** @liguanlong
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#112]</sub>

**Comment by ghost** [comment]
update the UserGuide. Thanks!
