### ISSUE TITLE
Search command in Command Summary in User Guide, but Search Command not found

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#135]
**Describe the bug**
Search command in Command Summary in User Guide, but Search Command not found

**To Reproduce**
`search`

**Screenshots**
<img width="872" alt="Screenshot 2019-04-03 at 1 01 20 PM" src="https://user-images.githubusercontent.com/32394182/55453980-a76e4d00-5610-11e9-940d-bd1e61e5bf6b.png">

<hr>

**Reported by:** @marcus-pzj
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#122]</sub>

**Comment by cheahzk** [comment]
#147 There is a mistake in the user guide, done the updating. Thanks.
