### ISSUE TITLE
add command can be upgraded

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#136]
Hi! I tried inputting "a n/Revise CS2113T"

![image](https://user-images.githubusercontent.com/3040701/55453853-2fa02280-5610-11e9-8a08-012ab0d71fe7.png)

As a user (not sure about the rest), I would like to just add my tasks and worry about the details later. For example, I wouldnt know when to revise CS2113T until I finish another assignment. So I would like to add a revise CS2113T reminder and input the details later, after finishing the assignment. Thanks!

<hr>

**Reported by:** @sameow
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#125]</sub>

**Comment by cheahzk** [comment]
As our project aims to help students to plan their time for all tasks, it is much more efficient to plan when you include all the details. Should you have a change in that plan, you can always edit the task details. 
Hopefully it clarifies your doubts. Thanks.
