### ISSUE TITLE
timeline does not work properly

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#137]
**Describe the bug**
Timeline does not work as desired. It shows an empty timeline and displays the timeline of a date when the task does not exist.

**To Reproduce**
1. clear the tasks
2. add another task
3. type in 'timeline'

**Expected behavior**
I would expect a valid timeline to pop up if any task exist on that particular day.
An error message should appear if there isn't any task.

In the screenshot, we can see that there are no 03/04/2019 tasks however the display result box talks about it.

Also, after i have added a 03/04/2019 task, nothing pops up on the timeline

![image](https://user-images.githubusercontent.com/34192985/55453897-552d2c00-5610-11e9-84bb-3772adc5d096.png)

<hr>

**Reported by:** @jayrometan
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#133]</sub>

**Comment by ghost** [comment]
@jingchen-z

**Comment by jingchen-z** [comment]
Our consideration is that an empty timeline is also a timeline, just like a day is still a day even if you do not have anything to do. As for the task not showing, it is clarified in the UserGuide that 'timeline' is not just UI, it is a functionality. So rearranging the timeline will show the newly added task. Hope this clarifies you question. :)
