### ISSUE TITLE
The UserGuide does not match the behaviour of the add command 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#138]
**Describe the bug**
The example format of command add cannot work in the application.

**To Reproduce**
1. Open the jar file.
2. Type  "add n/TaskA CS2113 sd/17-03-19 st/10.00 ed/17-03-19 et/12.00 d/SomeTask" in the command line and press enter key.

**Expected behavior**
A task is successfully added.

**Screenshots**
According to the user guide, this format should be correct, but actually the add command cannot work when the category of the task is not specified.
![Screenshot from 2019-04-03 13-04-54](https://user-images.githubusercontent.com/36043330/55454196-85c19580-5611-11e9-9aae-d0128549aefe.png)

<hr>

**Reported by:** @liguanlong
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#155]</sub>

**Comment by cheahzk** [comment]
#147 Mistakes in user guide, done the updating.
