### ISSUE TITLE
example add command on user guide does not work

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#139]
The UG suggests the following command:
add n/CS2113 task sd/13-03-19 st/12.00 ed/13-03-19 et/14.00 d/Talk about version control
which is not accepted, probaby because the category is not added

add n/CS3235 lecture sd/13-03-19 st/08.00 ed/13-03-19 et/10.00 d/Talk about network security t/important
is also not accepted

<hr>

**Reported by:** @articstranger
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#162]</sub>

**Comment by cheahzk** [comment]
#147 Mistakes in the user guide, done the updating.
