### ISSUE TITLE
showTime does not work

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#140]
**Describe the bug**
The commands showTime do not work

**To Reproduce**
1. Type in showTime command
2. It says "Unknown command"

**Expected behavior**
I would expect some changes to be made.

<hr>

**Reported by:** @jayrometan
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#169]</sub>

**Comment by cheahzk** [comment]
#147 Mistakes in the user guide, updated the user guide.
