### ISSUE TITLE
Edit command has some errors

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#141]
**Describe the bug**
Edit command allows you to change the end date of the task to be earlier than the start date of the task

**To Reproduce**
1. Enter any task.
2. Change the end date of the task to be earlier than the start date of the task.
3. It goes through

**Expected behavior**
I would expect to see an error message, like the error in the add command.

<hr>

**Reported by:** @jayrometan
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#191]</sub>

**Comment by cheahzk** [comment]
#147 Added checks for date and time in edit command.
