### ISSUE TITLE
2 activities in same timeslot

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#142]
**To Reproduce**
input "a n/R sd/15-03-19 st/14.00 ed/15-03-19 et/17.00 d/test c/a"

**Expected behavior**
It should show error that says clash with the first activity

**Screenshots**
![image](https://user-images.githubusercontent.com/3040701/55454546-df768f80-5612-11e9-8758-a676dca90b62.png)

<hr>

**Reported by:** @sameow
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#205]</sub>

**Comment by cheahzk** [comment]
Hi, technically, that 2 task names are still different from each other, one is "R", the other is "Revise CS2113T" so there is no confusion between that 2 tasks. It is allowed in this case. Hopefully, it clears your doubts. Thanks.
