### ISSUE TITLE
UserGuide does not match help function in the application

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#143]
**Describe the bug**
UserGuide does not match help function in the application. The showTime command is not in the content displayed in the help command, the time timeline command is not in the UserGuide 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

<hr>

**Reported by:** @liguanlong
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#208]</sub>

**Comment by cheahzk** [comment]
#147 Updated the user guide to prevent confusion.
