### ISSUE TITLE
Autocompletion feature and wrong command suggestion does not cover all commands

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-2/main#144]
**Describe the bug**
Autocompletion feature and wrong command suggestion does not cover all commands. Eg. remind
<img width="426" alt="Screenshot 2019-04-03 at 1 11 31 PM" src="https://user-images.githubusercontent.com/32394182/55454585-fcab5e00-5612-11e9-9a9a-b1b24a7c3697.png">

<hr>

**Reported by:** @marcus-pzj
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#213]</sub>

**Comment by ghost** [comment]
updated wrong command suggestion. Thanks
